In [1]:
#import library
import numpy as np
import pandas as pd

In [2]:
#read dataset
df_movie = pd.read_csv('C:\\rohit\\simple\\pratice project 3\\Amazon - Movies and TV Ratings.csv')

In [3]:
#describe
df_movie.describe()

Movie1  Movie2  Movie3  Movie4     Movie5  Movie6  Movie7  Movie8  \
count     1.0     1.0     1.0     2.0  29.000000     1.0     1.0     1.0   
mean      5.0     5.0     2.0     5.0   4.103448     4.0     5.0     5.0   
std       NaN     NaN     NaN     0.0   1.496301     NaN     NaN     NaN   
min       5.0     5.0     2.0     5.0   1.000000     4.0     5.0     5.0   
25%       5.0     5.0     2.0     5.0   4.000000     4.0     5.0     5.0   
50%       5.0     5.0     2.0     5.0   5.000000     4.0     5.0     5.0   
75%       5.0     5.0     2.0     5.0   5.000000     4.0     5.0     5.0   
max       5.0     5.0     2.0     5.0   5.000000     4.0     5.0     5.0   

       Movie9  Movie10  ...  Movie197  Movie198  Movie199  Movie200  Movie201  \
count     1.0      1.0  ...  5.000000       2.0       1.0  8.000000  3.000000   
mean      5.0      5.0  ...  3.800000       5.0       5.0  4.625000  4.333333   
std       NaN      NaN  ...  1.643168       0.0       NaN  0.517549  1.154701   
min       5.0      5.0  ...  1.000000       5.0       5.0  4.000000  3.000000   
25%       5.0      5.0  ...  4.000000       5.0       5.0  4.000000  4.000000   
50%       5.0      5.0  ...  4.000000       5.0       5.0  5.000000  5.000000   
75%       5.0      5.0  ...  5.000000       5.0       5.0  5.000000  5.000000   
max       5.0      5.0  ...  5.000000       5.0       5.0  5.000000  5.000000   

       Movie202  Movie203  Movie204   Movie205   Movie206  
count  6.000000       1.0  8.000000  35.000000  13.000000  
mean   4.333333       3.0  4.375000   4.628571   4.923077  
std    1.632993       NaN  1.407886   0.910259   0.277350  
min    1.000000       3.0  1.000000   1.000000   4.000000  
25%    5.000000       3.0  4.750000   5.000000   5.000000  
50%    5.000000       3.0  5.000000   5.000000   5.000000  
75%    5.000000       3.0  5.000000   5.000000   5.000000  
max    5.000000       3.0  5.000000   5.000000   5.000000  

[8 rows x 206 columns]

In [4]:
#info
df_movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4848 entries, 0 to 4847
Columns: 207 entries, user_id to Movie206
dtypes: float64(206), object(1)
memory usage: 7.7+ MB


In [7]:
#count
df_movie.count()

user_id     4848
Movie1         1
Movie2         1
Movie3         1
Movie4         2
            ... 
Movie202       6
Movie203       1
Movie204       8
Movie205      35
Movie206      13
Length: 207, dtype: int64

In [8]:
#add column count#
#df_movie['count']=df_movie.count()

In [9]:
#print the columns
df_movie.columns

Index(['user_id', 'Movie1', 'Movie2', 'Movie3', 'Movie4', 'Movie5', 'Movie6',
       'Movie7', 'Movie8', 'Movie9',
       ...
       'Movie197', 'Movie198', 'Movie199', 'Movie200', 'Movie201', 'Movie202',
       'Movie203', 'Movie204', 'Movie205', 'Movie206'],
      dtype='object', length=207)

In [10]:
#print user id
df_movie['user_id']

0       A3R5OBKS7OM2IR
1        AH3QC2PC1VTGP
2       A3LKP6WPMP9UKX
3        AVIY68KEPQ5ZD
4       A1CV1WROP5KTTW
             ...      
4843    A1IMQ9WMFYKWH5
4844    A1KLIKPUF5E88I
4845     A5HG6WFZLO10D
4846    A3UU690TWXCG1X
4847     AI4J762YI6S06
Name: user_id, Length: 4848, dtype: object

In [11]:
#High Viewership having lowest count  of no rating.
df_movie_no_rating = df_movie.isnull().sum().sort_values(ascending=True)
df_movie_no_rating = df_movie_no_rating[df_movie_no_rating>0]
df_movie_no_rating.head(5)

Movie127    2535
Movie140    4270
Movie16     4528
Movie103    4576
Movie29     4605
dtype: int64

In [12]:
#lowest Viewership having highest count  of no rating.
df_movie_no_rating.tail(5)

Movie2      4847
Movie66     4847
Movie67     4847
Movie153    4847
Movie146    4847
dtype: int64

In [13]:
#replace null values by 0
df_movie.fillna(0)
#df1.fillna(df1.mean()) replace with mean

user_id  Movie1  Movie2  Movie3  Movie4  Movie5  Movie6  Movie7  \
0     A3R5OBKS7OM2IR     5.0     5.0     0.0     0.0     0.0     0.0     0.0   
1      AH3QC2PC1VTGP     0.0     0.0     2.0     0.0     0.0     0.0     0.0   
2     A3LKP6WPMP9UKX     0.0     0.0     0.0     5.0     0.0     0.0     0.0   
3      AVIY68KEPQ5ZD     0.0     0.0     0.0     5.0     0.0     0.0     0.0   
4     A1CV1WROP5KTTW     0.0     0.0     0.0     0.0     5.0     0.0     0.0   
...              ...     ...     ...     ...     ...     ...     ...     ...   
4843  A1IMQ9WMFYKWH5     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4844  A1KLIKPUF5E88I     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4845   A5HG6WFZLO10D     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4846  A3UU690TWXCG1X     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4847   AI4J762YI6S06     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

      Movie8  Movie9  ...  Movie197  Movie198  Movie199  Movie200  Movie201  \
0        0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
1        0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
2        0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
3        0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
4        0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
...      ...     ...  ...       ...       ...       ...       ...       ...   
4843     0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
4844     0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
4845     0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
4846     0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   
4847     0.0     0.0  ...       0.0       0.0       0.0       0.0       0.0   

      Movie202  Movie203  Movie204  Movie205  Movie206  
0          0.0       0.0       0.0       0.0       0.0  
1          0.0       0.0       0.0       0.0       0.0  
2          0.0       0.0       0.0       0.0       0.0  
3          0.0       0.0       0.0       0.0       0.0  
4          0.0       0.0       0.0       0.0       0.0  
...        ...       ...       ...       ...       ...  
4843       0.0       0.0       0.0       0.0       5.0  
4844       0.0       0.0       0.0       0.0       5.0  
4845       0.0       0.0       0.0       0.0       5.0  
4846       0.0       0.0       0.0       0.0       5.0  
4847       0.0       0.0       0.0       0.0       5.0  

[4848 rows x 207 columns]

In [14]:
#describe
df_movie.describe()

Movie1  Movie2  Movie3  Movie4     Movie5  Movie6  Movie7  Movie8  \
count     1.0     1.0     1.0     2.0  29.000000     1.0     1.0     1.0   
mean      5.0     5.0     2.0     5.0   4.103448     4.0     5.0     5.0   
std       NaN     NaN     NaN     0.0   1.496301     NaN     NaN     NaN   
min       5.0     5.0     2.0     5.0   1.000000     4.0     5.0     5.0   
25%       5.0     5.0     2.0     5.0   4.000000     4.0     5.0     5.0   
50%       5.0     5.0     2.0     5.0   5.000000     4.0     5.0     5.0   
75%       5.0     5.0     2.0     5.0   5.000000     4.0     5.0     5.0   
max       5.0     5.0     2.0     5.0   5.000000     4.0     5.0     5.0   

       Movie9  Movie10  ...  Movie197  Movie198  Movie199  Movie200  Movie201  \
count     1.0      1.0  ...  5.000000       2.0       1.0  8.000000  3.000000   
mean      5.0      5.0  ...  3.800000       5.0       5.0  4.625000  4.333333   
std       NaN      NaN  ...  1.643168       0.0       NaN  0.517549  1.154701   
min       5.0      5.0  ...  1.000000       5.0       5.0  4.000000  3.000000   
25%       5.0      5.0  ...  4.000000       5.0       5.0  4.000000  4.000000   
50%       5.0      5.0  ...  4.000000       5.0       5.0  5.000000  5.000000   
75%       5.0      5.0  ...  5.000000       5.0       5.0  5.000000  5.000000   
max       5.0      5.0  ...  5.000000       5.0       5.0  5.000000  5.000000   

       Movie202  Movie203  Movie204   Movie205   Movie206  
count  6.000000       1.0  8.000000  35.000000  13.000000  
mean   4.333333       3.0  4.375000   4.628571   4.923077  
std    1.632993       NaN  1.407886   0.910259   0.277350  
min    1.000000       3.0  1.000000   1.000000   4.000000  
25%    5.000000       3.0  4.750000   5.000000   5.000000  
50%    5.000000       3.0  5.000000   5.000000   5.000000  
75%    5.000000       3.0  5.000000   5.000000   5.000000  
max    5.000000       3.0  5.000000   5.000000   5.000000  

[8 rows x 206 columns]

In [15]:
#convert movie column to row
final=pd.melt(df_movie, id_vars =['user_id'], value_vars =df_movie.columns[1:].values) 

In [16]:
#print first five records
final.head(5)

user_id variable  value
0  A3R5OBKS7OM2IR   Movie1    5.0
1   AH3QC2PC1VTGP   Movie1    NaN
2  A3LKP6WPMP9UKX   Movie1    NaN
3   AVIY68KEPQ5ZD   Movie1    NaN
4  A1CV1WROP5KTTW   Movie1    NaN

In [17]:
#info
final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998688 entries, 0 to 998687
Data columns (total 3 columns):
user_id     998688 non-null object
variable    998688 non-null object
value       5000 non-null float64
dtypes: float64(1), object(2)
memory usage: 22.9+ MB


In [18]:
#Print last five records
final.tail(5)

user_id  variable  value
998683  A1IMQ9WMFYKWH5  Movie206    5.0
998684  A1KLIKPUF5E88I  Movie206    5.0
998685   A5HG6WFZLO10D  Movie206    5.0
998686  A3UU690TWXCG1X  Movie206    5.0
998687   AI4J762YI6S06  Movie206    5.0

In [19]:
#movie rating
df_group = final.groupby(['value','variable'])['value'].mean().sort_values(ascending=False)

In [20]:
#Movie with high rating
df_group.head()

value  variable
5.0    Movie99     5.0
       Movie187    5.0
       Movie162    5.0
       Movie161    5.0
       Movie160    5.0
Name: value, dtype: float64

In [21]:
#Movie with low rating
df_group.tail()

value  variable
1.0    Movie89     1.0
       Movie90     1.0
       Movie91     1.0
       Movie95     1.0
       Movie103    1.0
Name: value, dtype: float64

In [22]:
#replace NAN with zero
df_final = final.fillna(0)

In [23]:
#rating
df_rating = df_final.groupby('value').size()
df_rating.head(10)

value
0.0    993688
1.0       363
2.0       185
3.0       272
4.0       521
5.0      3659
dtype: int64

In [24]:
df_rating.agg({'value':'mean'})

value    166448.0
dtype: float64

In [25]:
#replace NAN with mean  does not run  looks like infinite loop
#df_mean = final.fillna(final.mean())

#remove null values
df_clean=final[final['value'].notnull()]
df_clean.shape

(5000, 3)

In [26]:
#print first five record
df_final.head(5)

user_id variable  value
0  A3R5OBKS7OM2IR   Movie1    5.0
1   AH3QC2PC1VTGP   Movie1    0.0
2  A3LKP6WPMP9UKX   Movie1    0.0
3   AVIY68KEPQ5ZD   Movie1    0.0
4  A1CV1WROP5KTTW   Movie1    0.0

In [27]:
#print last five records
df_final.tail(5)

user_id  variable  value
998683  A1IMQ9WMFYKWH5  Movie206    5.0
998684  A1KLIKPUF5E88I  Movie206    5.0
998685   A5HG6WFZLO10D  Movie206    5.0
998686  A3UU690TWXCG1X  Movie206    5.0
998687   AI4J762YI6S06  Movie206    5.0

In [28]:
#Select features from the dataset to create the model
feature_select_cols = ['user_id','variable']
#Create the feature object
X_feature = df_final[feature_select_cols] # with null replaced with zeros
X_clean = df_clean[feature_select_cols]   # null values removed

In [29]:
#print feature data
X_feature

user_id  variable
0       A3R5OBKS7OM2IR    Movie1
1        AH3QC2PC1VTGP    Movie1
2       A3LKP6WPMP9UKX    Movie1
3        AVIY68KEPQ5ZD    Movie1
4       A1CV1WROP5KTTW    Movie1
...                ...       ...
998683  A1IMQ9WMFYKWH5  Movie206
998684  A1KLIKPUF5E88I  Movie206
998685   A5HG6WFZLO10D  Movie206
998686  A3UU690TWXCG1X  Movie206
998687   AI4J762YI6S06  Movie206

[998688 rows x 2 columns]

In [30]:
#print feature data with no null values
X_clean

user_id  variable
0       A3R5OBKS7OM2IR    Movie1
4848    A3R5OBKS7OM2IR    Movie2
9697     AH3QC2PC1VTGP    Movie3
14546   A3LKP6WPMP9UKX    Movie4
14547    AVIY68KEPQ5ZD    Movie4
...                ...       ...
998683  A1IMQ9WMFYKWH5  Movie206
998684  A1KLIKPUF5E88I  Movie206
998685   A5HG6WFZLO10D  Movie206
998686  A3UU690TWXCG1X  Movie206
998687   AI4J762YI6S06  Movie206

[5000 rows x 2 columns]

In [31]:
#Create the target object
Y_target = df_final['value'] # with null replaced with zeros
Y_clean = df_clean['value']  # null values removed

In [32]:
#import KNN from sklearn
from sklearn.neighbors import KNeighborsClassifier

In [33]:
#instantiate KNN estimator
knn = KNeighborsClassifier(n_neighbors=1)

In [34]:
#print the knn
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')


In [35]:
#Split the dataset to test and train the model with user id and movie name as feature
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X_feature,Y_target,random_state=1)
x_train

user_id  variable
336451   AMSAQB9DNQRUS   Movie70
501095  A1V4QPN5W2WS8T  Movie104
976524  A1UO5RU0DV7ZIG  Movie202
528927  A2UKWIDERJ8IHA  Movie110
468437  A2UL0A8GJB4318   Movie97
...                ...       ...
491263  A3IY2JLE4X829W  Movie102
791624  A1H143CZ4AM6VO  Movie164
470924  A35RXHCGGWEXQH   Movie98
491755  A1T8CV2VBAFXZO  Movie102
128037  A3AGZG0PDAGCK3   Movie27

[749016 rows x 2 columns]

In [36]:
#Split the dataset to test and train clean data no null values
from sklearn.model_selection import train_test_split
x_train_c,x_test_c,y_train_c,y_test_c = train_test_split(X_clean,Y_clean,random_state=1)
x_train_c

user_id  variable
613933   AF18LCM3NQQG6  Movie127
136375  A2JSR55IWC7HWO   Movie29
136320   AYCT65TQ1PLL4   Movie29
613153  A15G80TVI5M8IR  Movie127
780248  A2G5SNWDL61VJ7  Movie161
...                ...       ...
613642  A21A17T3TG912R  Movie127
613510  A3HVAHHHY9D7AC  Movie127
437207  A1E8OGV9SO0E0P   Movie91
672889   ANYDEWJQN2GBX  Movie139
72954   A2F3GFAA3XQDIB   Movie16

[3750 rows x 2 columns]

In [37]:
#import LabelEncoder from sklearn
from sklearn.preprocessing import LabelEncoder
#instantiate LabelEncoder
number = LabelEncoder()
#Transform non-numerical label to numerical label and create train , test data
x_train.user_id = number.fit_transform(x_train["user_id"].astype("str"))
x_test.user_id = number.fit_transform(x_test["user_id"].astype("str"))
x_train.variable = number.fit_transform(x_train["variable"].astype("str"))
x_test.variable = number.fit_transform(x_test["variable"].astype("str"))
y_train = number.fit_transform(y_train.astype("int"))
y_test = number.fit_transform(y_test.astype("int"))

C:\Users\win10\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [38]:
#Transform non-numerical label to numerical label and create train , test data for clean data with no null values
x_train_c.user_id = number.fit_transform(x_train_c["user_id"].astype("str"))
x_test_c.user_id = number.fit_transform(x_test_c["user_id"].astype("str"))
x_train_c.variable = number.fit_transform(x_train_c["variable"].astype("str"))
x_test_c.variable = number.fit_transform(x_test_c["variable"].astype("str"))
y_train_c = number.fit_transform(y_train_c.astype("int"))
y_test_c = number.fit_transform(y_test_c.astype("int"))

In [39]:
#print shape of training data
x_train.shape
x_train

user_id  variable
336451     4390       174
501095     1095         6
976524     1078       115
528927     2409        13
468437     2410       203
...         ...       ...
491263     3249         4
791624      607        72
470924     2788       204
491755     1026         4
128037     2963       126

[749016 rows x 2 columns]

In [40]:
#print shape of training data
x_train_c.shape


(3750, 2)

In [41]:
#print first five records of training data
x_train.head(5)

user_id  variable
336451     4390       174
501095     1095         6
976524     1078       115
528927     2409        13
468437     2410       203

In [42]:
#fit data in KNN estimator with movie and userid as feature
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [43]:
#fit data in KNN estimator with clean data no null values
knn.fit(x_train_c,y_train_c)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [44]:
#Testing
predicted = knn.predict(x_test)
predicted

array([4, 4, 4, ..., 1, 1, 1], dtype=int64)

In [45]:
#testing with  clean data with no null values
predicted_clean = knn.predict(x_test_c)
predicted_clean

array([1, 4, 4, ..., 0, 4, 2], dtype=int64)

In [46]:
#Evaluate the accuracy of model with null replaced with zero
from sklearn import metrics
x= metrics.accuracy_score(y_test,predicted)
print(x)

0.04123009388317472


In [47]:
#Evaluate the accuracy of model with null removed
from sklearn import metrics
x_c= metrics.accuracy_score(y_test_c,predicted_clean)
print(x_c)

0.5528


In [48]:
#Confusion Matrix with null replaced with zero
from sklearn import metrics
print(metrics.confusion_matrix(y_test, predicted))

[[ 10192  38511  28578  19019 152110      0]
 [     7     28      4      6     35      0]
 [     4     11      2      8     31      0]
 [     5     13      4      5     33      0]
 [    14     23      7      5     67      0]
 [    50    218     59     78    545      0]]


In [49]:
#Confusion Matrix with clean data no null values
from sklearn import metrics
print(metrics.confusion_matrix(y_test_c, predicted_clean))

[[  7   7   5   8  58]
 [  4   2   3   1  35]
 [  7   1   6   2  56]
 [  8   4   7  18 108]
 [ 62  29  50 104 658]]


In [50]:
#Classification Report with null replaced with zero
print(metrics.classification_report(y_test, predicted))

C:\Users\win10\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

           0       0.99      0.04      0.08    248410
           1       0.00      0.35      0.00        80
           2       0.00      0.04      0.00        56
           3       0.00      0.08      0.00        60
           4       0.00      0.58      0.00       116
           5       0.00      0.00      0.00       950

    accuracy                           0.04    249672
   macro avg       0.17      0.18      0.01    249672
weighted avg       0.99      0.04      0.08    249672



In [51]:
#Classification Report with clean data
print(metrics.classification_report(y_test_c, predicted_clean))

              precision    recall  f1-score   support

           0       0.08      0.08      0.08        85
           1       0.05      0.04      0.05        45
           2       0.08      0.08      0.08        72
           3       0.14      0.12      0.13       145
           4       0.72      0.73      0.72       903

    accuracy                           0.55      1250
   macro avg       0.21      0.21      0.21      1250
weighted avg       0.55      0.55      0.55      1250



In [52]:
# Create a logistic regression model using the training set
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [53]:
#Training with null replaced with zero
logreg.fit(x_train,y_train)

C:\Users\win10\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\win10\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [54]:
#Training with clean data no null values
logreg.fit(x_train_c,y_train_c)

C:\Users\win10\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\win10\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
#Make predictions using the testing set with null replaced with zero
y_pred = logreg.predict(x_test)

In [56]:
#Make predictions using the testing set clean data no null values
y_pred_c = logreg.predict(x_test_c)

In [57]:
#Evaluate the accuracy of model with null replaced with zero
from sklearn import metrics
x= metrics.accuracy_score(y_test,y_pred)
print(x)

0.0004646095677528918


In [58]:
#Evaluate the accuracy of model of clean data with no null values
from sklearn import metrics
x_c= metrics.accuracy_score(y_test_c,y_pred_c)
print(x_c)

0.7224


In [59]:
#Confusion Matrix with null replaced with zero
from sklearn import metrics
print(metrics.confusion_matrix(y_test, y_pred))

[[     0      0      0      0 248410      0]
 [     0      0      0      0     80      0]
 [     0      0      0      0     56      0]
 [     0      0      0      0     60      0]
 [     0      0      0      0    116      0]
 [     0      0      0      0    950      0]]


In [60]:
#Confusion Matrix of clean data with no null values
from sklearn import metrics
print(metrics.confusion_matrix(y_test_c, y_pred_c))

[[  0   0   0   0  85]
 [  0   0   0   0  45]
 [  0   0   0   0  72]
 [  0   0   0   0 145]
 [  0   0   0   0 903]]


In [61]:
#Classification Report with null replaced with zero
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00    248410
           1       0.00      0.00      0.00        80
           2       0.00      0.00      0.00        56
           3       0.00      0.00      0.00        60
           4       0.00      1.00      0.00       116
           5       0.00      0.00      0.00       950

    accuracy                           0.00    249672
   macro avg       0.00      0.17      0.00    249672
weighted avg       0.00      0.00      0.00    249672



C:\Users\win10\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [62]:
#Classification Report clean data with no null values
print(metrics.classification_report(y_test_c, y_pred_c))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        85
           1       0.00      0.00      0.00        45
           2       0.00      0.00      0.00        72
           3       0.00      0.00      0.00       145
           4       0.72      1.00      0.84       903

    accuracy                           0.72      1250
   macro avg       0.14      0.20      0.17      1250
weighted avg       0.52      0.72      0.61      1250

